### PR TITLE
Added AnimeGameSystem(AGS) Packer and Unpacker

### PR DESCRIPTION
**Pull request by HOKORISAMA**
Hello again, I've added Unpacker and Packer for AGS (Only works for unencrypted games for now).

### CODE REVIEW

**Comment by HOKORISAMA** [comment]
it's used by [Erogos](https://vndb.org/v269).

**Comment by detached64** [comment]
Merged. Thanks for your contribution.

**Comment by detached64** [comment]
I imported AGS schemes from GARbroDB. Feel free to add schemes to [Formats.json](https://github.com/detached64/GalArc/blob/master/GalArc.GUI/Resources/Extensions/Formats.json).

**Comment by HOKORISAMA** [comment]
> I imported AGS schemes from GARbroDB. Feel free to add schemes to [Formats.json](https://github.com/detached64/GalArc/blob/master/GalArc.GUI/Resources/Extensions/Formats.json).

Sure, I'll look in it when I'll have time.

**Pull request merged**
